
TestMaze: MazeNode.h Maze.h Maze.o MazeNode.o TestMaze.cpp
	g++ -g MazeNode.cpp Maze.cpp TestMaze.cpp -o TestMaze

Maze.o: Maze.cpp Maze.h
	g++ -c Maze.cpp

MazeNode.o: MazeNode.h MazeNode.cpp
	g++ -c MazeNode.cpp